"""
CyberQuill Data Models (Schemas)
==================================

Purpose:
    Defines the data structures that flow between agents. Every agent
    knows exactly what data it receives and what it must produce.
    Think of these as "contracts" — if an agent produces data that
    doesn't match the schema, Pydantic raises an error immediately.

Why Pydantic models?
    1. Type safety — catches bugs early (e.g., missing fields)
    2. Self-documenting — the schema IS the documentation
    3. Serialization — easy conversion to/from JSON
    4. Validation — automatic type checking and coercion

How data flows through the pipeline:
    Collector  → Article
    Duplicate  → Article (filtered list)
    Classifier → ClassifiedArticle (Article + category)
    RAG        → EnrichedArticle (ClassifiedArticle + RAG context)
    Writer     → MagazineArticle (full generated article)
    Reviewer   → ReviewedArticle (MagazineArticle + review)

Inputs:
    - Raw data from RSS feeds, LLM responses, etc.

Outputs:
    - Validated, typed Python objects

Dependencies:
    - pydantic

Testing strategy:
    - Test each model with valid data → should create successfully
    - Test with missing required fields → should raise ValidationError
    - Test serialization → .model_dump() and .model_dump_json() should work
    - Test from JSON → Model.model_validate_json() should parse correctly

Possible improvements:
    - Add custom validators (e.g., URL format validation)
    - Add computed fields (e.g., word count for articles)
    - Add model versioning for backward compatibility
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


# ============================================
# Stage 1: Collector Agent Output
# ============================================

class Article(BaseModel):
    """
    Represents a single news article collected from an RSS feed.
    
    This is the FIRST data structure in the pipeline.
    The Collector Agent creates these from raw RSS feed entries.
    
    Fields:
        title: The headline of the article
        link: URL to the full article
        source: Which RSS feed/publication it came from
        published: When the article was published
        summary: Brief description or first paragraph
    """
    title: str = Field(
        ...,  # ... means this field is REQUIRED
        description="The headline of the article"
    )
    link: str = Field(
        ...,
        description="URL to the full article"
    )
    source: str = Field(
        ...,
        description="Name of the publication (e.g., 'The Hacker News')"
    )
    published: str = Field(
        default="",
        description="Publication date as a string"
    )
    summary: str = Field(
        default="",
        description="Brief description or first paragraph of the article"
    )


# ============================================
# Stage 2: Classification Agent Output
# ============================================

class ClassifiedArticle(Article):
    """
    An Article with an added category label.
    
    Inherits ALL fields from Article and adds:
        category: The threat category assigned by the Classification Agent
        confidence: How confident the classifier is (0.0 to 1.0)
    
    Why inherit from Article?
        - Avoids duplicating all the Article fields
        - A ClassifiedArticle IS an Article (with extra info)
        - This is called "inheritance" in OOP
    """
    category: str = Field(
        default="Uncategorized",
        description="Threat category (e.g., 'Malware', 'Data Breach')"
    )
    confidence: float = Field(
        default=0.0,
        ge=0.0,  # ge = greater than or equal to
        le=1.0,  # le = less than or equal to
        description="Classification confidence score (0.0 to 1.0)"
    )
    classification_method: str = Field(
        default="",
        description="Method used: llm, keyword, forced_llm, best_guess, uncategorized"
    )


# ============================================
# Stage 3: RAG Agent Output
# ============================================

class EnrichedArticle(ClassifiedArticle):
    """
    A ClassifiedArticle enriched with context from the RAG knowledge base.
    
    Adds:
        rag_context: Relevant text retrieved from the vector database
        rag_sources: List of source document names used for enrichment
    """
    rag_context: str = Field(
        default="",
        description="Retrieved context from the RAG knowledge base"
    )
    rag_sources: list[str] = Field(
        default_factory=list,
        description="List of source documents used for enrichment"
    )


# ============================================
# Stage 4: Writer Agent Output
# ============================================

class MagazineArticle(BaseModel):
    """
    A full magazine-style article generated by the Writer Agent.
    
    Note: This does NOT inherit from Article because it's a completely
    different structure. It's a generated article, not a collected one.
    
    The Writer Agent takes an EnrichedArticle as input and produces
    this as output.
    """
    title: str = Field(
        ...,
        description="Generated magazine article title"
    )
    executive_summary: str = Field(
        default="",
        description="2-3 sentence overview"
    )
    background: str = Field(
        default="",
        description="Context and history of the threat/topic"
    )
    technical_analysis: str = Field(
        default="",
        description="Detailed technical breakdown"
    )
    impact: str = Field(
        default="",
        description="Who is affected and how"
    )
    recommendations: str = Field(
        default="",
        description="Actionable security recommendations"
    )
    references: str = Field(
        default="",
        description="Sources used"
    )
    original_link: str = Field(
        default="",
        description="Link to the original article"
    )
    category: str = Field(
        default="",
        description="Category of the original article"
    )
    generated_at: str = Field(
        default_factory=lambda: datetime.now().isoformat(),
        description="Timestamp when the article was generated"
    )


# ============================================
# Stage 5: Reviewer Agent Output
# ============================================

class ReviewResult(BaseModel):
    """
    The output of the Reviewer Agent's review process.
    
    Contains the review decision, score, and any issues found.
    If the article is not approved, it may be sent back to the
    Writer Agent for revision (reflection pattern).
    """
    quality_score: int = Field(
        default=0,
        ge=1,
        le=10,
        description="Quality rating from 1 to 10"
    )
    approved: bool = Field(
        default=False,
        description="Whether the article is approved for publication"
    )
    issues: list[str] = Field(
        default_factory=list,
        description="List of issues found during review"
    )
    revised_article: Optional[str] = Field(
        default=None,
        description="The revised article text, if changes were made"
    )
    review_notes: str = Field(
        default="",
        description="Editor's notes and feedback"
    )
    rag_fidelity_score: int = Field(
        default=10,
        ge=1,
        le=10,
        description="How well the article aligns with RAG knowledge base context (1-10)"
    )
    rag_issues: list[str] = Field(
        default_factory=list,
        description="Claims unsupported or contradicted by RAG context"
    )
